# Generated by Django 3.2.4 on 2022-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSeleccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='partidos',
            field=models.IntegerField(default=0),
        ),
    ]
