# Generated by Django 3.2.4 on 2022-01-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSeleccion', '0002_jugador_partidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torneo', models.CharField(max_length=40)),
                ('sede', models.CharField(max_length=40)),
                ('anio', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'TituloTabla',
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='titulos',
            field=models.ManyToManyField(to='WebSeleccion.Titulo'),
        ),
    ]
